name: py CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: upgrade
      run: sudo apt update; sudo apt install -y tzdata gcc g++ cmake
    - name: install py
      run: sudo apt install -y python3-matplotlib python3-numpy python3-pandas python3-scipy python3-xlrd python3-tk python3-requests poppler-utils ghostscript imagemagick libnotify-bin time git
    - name: chmod
      run: chmod +x CI_mpl_agg.sh; chmod +x run_all.sh; chmod +x make_md.sh; chmod +x merge.sh; 
    - name: compute
      run: sudo ./CI_mpl_agg.sh && ./run_all.sh 
    - name: make README.md
      run: ./make_md.sh
    - name: merge pdf
      run: ./merge.sh
    - name: git conf
      run: git config --global user.name "a-lemonnier"; git remote set-url origin https://a-lemonnier:${{ secrets.pass }}@github.com/a-lemonnier/crappy-code-covid.git
    - name: push
      run: git add --all; git commit -m "CI Update"; git push 
